openapi: 3.0.0
info:
  title: This is a sample of apartment rent advertisements
  description: 'Учебный проект - сайт по аренде недвижимости'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: advertisements
    description: Everything about apartment advertisements
paths:

  /advertisement:
    put:
      tags:
        - advertisements
      summary: Update an existing advertisement
      operationId: updateAd
      requestBody:
        description: Advertisement of apartment that needs to be updated to the site
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advertisement'
        required: true
      responses:
        405:
          description: Validation exception
          content: { }
    post:
      tags:
        - advertisements
      summary: Add a new advertisement to the site
      operationId: addAd
      requestBody:
        description: Advertisement of apartment that needs to be updated to the site
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advertisement'
        required: true
      responses:
        "200":
          description: Успех
          content: { }

  /advertisement/{id}:
    post:
      tags:
        - advertisements
      summary: Gets an advertisement by ID.
      operationId: getAdById
      parameters:
        - name: id
          in: path
          description: advertisement ID
          required: true
          schema:
            type: string
            title: id
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advertisement'

    delete:
      tags:
        - "advertisements"
      summary: "Delete an advertisement"
      description: ""
      operationId: "deleteAdvertisement"
      parameters:
        - in: path
          name: id
          schema:
            type: string
            title: id
          required: true
          description: The user ID.
      responses:
        '204':
          description: Ad was deleted.

components:
  schemas:

    Advertisement:
      type: object
      properties:
        id:
          type: string
          title: id
        adOwner:
          type: object
          $ref: '#/components/schemas/User'
        property:
          type: object
          $ref: '#/components/schemas/Property'
        dateFrom:
          type: string
          format: date-time
        dateTill:
          type: string
          format: date-time
        active:
          type: boolean
          description: Объявление активно (Да/ Нет)
      required:
        - id
        - adOwner
        - property
        - dateFrom
        - dateTill
        - status
        - active



    User:
      type: object
      title: Пользователь
      properties:
        id:
          type: string
          title: id
        firstName:
          type: string
          title: Имя пользователя
        secondName:
          type: string
          title: Фамилия пользователя
      required:
      - id


    Address:
      type: object
      title: Адрес местонахождения объекта недвижимости
      properties:
        county:
          type: string
          title: Регион местонахождения объекта недвижимости
        distinct:
          type: string
          title: Район местонахождения объекта недвижимости
        city:
          type: string
          title: Город местонахождения объекта недвижимости
        street:
          type: string
          title: Улица местонахождения объекта недвижимости
        buildNumber:
          type: string
          title: Номер дома/строения местонахождения объекта недвижимости

    Property:
      type: object
      title: Недвижимость
      properties:
        id:
          type: string
          title: id
        propertyType:
          type: string
          description: Тип недвижимости
          enum:
            - flat
            - house
            - room
        price:
          type: object
          $ref: '#/components/schemas/Money'
        address:
          type: object
          $ref: '#/components/schemas/Address'
        countOfRooms:
          type: integer
          description: Количество комнат
        countOfBaths:
          type: integer
          description: Количество ванных комнат
        square:
          type: double
          description: Площадь объекта недвижимости
        furnished:
          type: boolean
          description: Мебилирован объект недвижимости да/нет
        lease:
          type: object
          $ref: '#/components/schemas/Lease'
      required:
        - id
        - propertyType
        - price
        - address
        - countOfRooms
        - countOfBaths
        - square
        - furnished
        - lease

    Money:
      type: object
      title: Деньги
      properties:
        amount:
          type: number
          format: integer
        currencyCode:
          type: string
          description: Валюта
    Lease:
      type: string
      description: Срок аренды
      enum:
        - hour
        - day
        - week
        - month
        - half_of_year
        - one_year_and_more

    

